artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: C:/Users/ashwi/OneDrive/Desktop/DevRev07/Under-Water-Animal-Classification/sea animal.zip
  unzip_dir: artifacts/data_ingestion
  
prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
  
